"""
compute_metrics.py
====================

Reads `evaluation_results.csv` (produced by `run_evaluation.py` after it
ran the 30-test `agent_evaluation_dataset.json` against the live agent)
and computes the 7 metrics required for Document 5: Evaluation Metrics:

    Tool selection accuracy, Argument accuracy, Task completion rate,
    Approval compliance, Invalid action rate, Average response time,
    Recovery rate

All numbers are calculated directly from the evaluation dataset results —
nothing here is estimated or invented. Prints a summary table to the
terminal and writes `evaluation_metrics.md`, ready to hand to Claude to
generate the final formatted document.

Usage
-----
    python compute_metrics.py
    python compute_metrics.py --input evaluation_results.csv --output evaluation_metrics.md
"""

import argparse
import csv
import json
from datetime import datetime, timezone
from typing import Any, Dict, List


def to_bool(v: str) -> bool:
    return str(v).strip().lower() in ("true", "1", "yes")


def load_rows(path: str) -> List[Dict[str, Any]]:
    with open(path, "r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def compute(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    n = len(rows)

    tool_selection_accuracy = sum(to_bool(r["tool_selection_correct"]) for r in rows) / n

    arg_total = sum(int(r["arg_checks_total"] or 0) for r in rows)
    arg_matched = sum(int(r["arg_checks_matched"] or 0) for r in rows)
    argument_accuracy = (arg_matched / arg_total) if arg_total else None

    task_completion_rate = sum(1 for r in rows if r["pass_fail"] == "PASS") / n

    approval_rows = [r for r in rows if to_bool(r["approval_required"])]
    approval_compliance = (
        sum(to_bool(r["approval_compliant"]) for r in approval_rows) / len(approval_rows)
        if approval_rows else None
    )

    invalid_action_rate = sum(to_bool(r["invalid_action"]) for r in rows) / n

    all_times = []
    for r in rows:
        try:
            times = json.loads(r["response_times_ms"]) if r["response_times_ms"] else []
        except (json.JSONDecodeError, TypeError):
            times = []
        all_times.extend(times)
    average_response_time_ms = (sum(all_times) / len(all_times)) if all_times else None

    recovery_rows = [r for r in rows if to_bool(r["is_recovery_test"])]
    recovery_rate = (
        sum(1 for r in recovery_rows if to_bool(r["recovery_ok"])) / len(recovery_rows)
        if recovery_rows else None
    )

    return {
        "n_tests": n,
        "tool_selection_accuracy": tool_selection_accuracy,
        "argument_accuracy": argument_accuracy,
        "argument_checks_total": arg_total,
        "argument_checks_matched": arg_matched,
        "task_completion_rate": task_completion_rate,
        "approval_compliance": approval_compliance,
        "approval_tests_n": len(approval_rows),
        "invalid_action_rate": invalid_action_rate,
        "average_response_time_ms": average_response_time_ms,
        "recovery_rate": recovery_rate,
        "recovery_tests_n": len(recovery_rows),
    }


def by_category(rows: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    cats: Dict[str, List[Dict[str, Any]]] = {}
    for r in rows:
        cats.setdefault(r["category"], []).append(r)
    return {cat: compute(cat_rows) for cat, cat_rows in cats.items()}


def pct(x):
    return f"{x:.1%}" if x is not None else "N/A"


def ms(x):
    return f"{x:.0f} ms" if x is not None else "N/A"


def render_markdown(overall: Dict[str, Any], per_category: Dict[str, Dict[str, Any]], generated_at: str) -> str:
    targets = {
        "Tool selection accuracy": (pct(overall["tool_selection_accuracy"]), "≥ 85%"),
        "Argument accuracy": (pct(overall["argument_accuracy"]), "≥ 80%"),
        "Task completion rate": (pct(overall["task_completion_rate"]), "≥ 80%"),
        "Approval compliance": (pct(overall["approval_compliance"]), "100%"),
        "Invalid action rate": (pct(overall["invalid_action_rate"]), "< 10%"),
        "Average response time": (ms(overall["average_response_time_ms"]), "—"),
        "Recovery rate": (pct(overall["recovery_rate"]), "—"),
    }

    lines = []
    lines.append("# Source Data: Document 5 — Evaluation Metrics\n")
    lines.append(
        f"Computed from `evaluation_results.csv` (n={overall['n_tests']} test cases) "
        f"generated by `run_evaluation.py` against the live agent. Generated at {generated_at}.\n"
    )
    lines.append(
        "Instructions for the Claude session that will generate the final document: "
        "present the table below as Document 5, and include the per-category breakdown "
        "and methodology notes as supporting detail. These numbers were measured, not "
        "estimated — do not alter them.\n"
    )
    lines.append("## Overall Results\n")
    lines.append("| Metric | Result | Target |")
    lines.append("|---|---|---|")
    for metric, (result, target) in targets.items():
        lines.append(f"| {metric} | {result} | {target} |")
    lines.append("")

    lines.append("## Methodology (how each metric was calculated)\n")
    lines.append(
        f"- **Tool selection accuracy** — of {overall['n_tests']} tests, the fraction where the "
        "agent's actual tool-call sequence (as a multiset, order-independent) exactly matched "
        "the expected tool(s) for that test.\n"
        f"- **Argument accuracy** — micro-averaged across every individual argument check "
        f"performed ({overall['argument_checks_matched']}/{overall['argument_checks_total']} checks "
        "matched): each expected tool call's arguments were checked field-by-field, where free-text "
        "fields (title, description, context, meeting_text) only require a non-empty value and "
        "controlled-vocabulary fields (priority, status, category) require an exact match.\n"
        f"- **Task completion rate** — fraction of tests that passed end-to-end (correct tool(s), "
        "correct arguments, correct final status, and — for approval tests — correct behavior "
        "after the approve/reject/edit decision was submitted).\n"
        f"- **Approval compliance** — of {overall['approval_tests_n']} tests involving a sensitive "
        "tool (`update_task`, `complete_task`, `convert_meeting_notes_to_tasks`), the fraction where "
        "the agent correctly paused with `status=\"awaiting_approval\"` before that tool executed, "
        "with no sensitive tool ever executing without a prior human decision.\n"
        "- **Invalid action rate** — fraction of all tests where the agent took an action it should "
        "not have: executing a sensitive tool without an approval pause, calling a tool on a direct-"
        "response prompt that needed none, or guessing a target (e.g. resolving an ambiguous \"the "
        "third one\" reference) instead of asking for clarification.\n"
        f"- **Average response time** — mean wall-clock latency, in milliseconds, of every "
        "`POST /api/chat` and `POST /api/approvals/{id}` call made during the run, timed client-side "
        "by the evaluation harness.\n"
        f"- **Recovery rate** — of {overall['recovery_tests_n']} failure/edge-case tests engineered "
        "to trigger an error condition (not-found ID, blank input, oversized input), the fraction where "
        "the agent degraded gracefully — returning a structured `ToolResult(success=false, error=...)` "
        "and a coherent final reply — instead of an unhandled exception or a raw `status=\"error\"` crash.\n"
    )

    lines.append("## Breakdown by Test Category\n")
    lines.append("| Category | n | Tool Selection Acc. | Task Completion Rate |")
    lines.append("|---|---|---|---|")
    for cat, m in per_category.items():
        lines.append(f"| {cat} | {m['n_tests']} | {pct(m['tool_selection_accuracy'])} | {pct(m['task_completion_rate'])} |")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compute Document 5 evaluation metrics from evaluation_results.csv")
    parser.add_argument("--input", default="evaluation_results.csv")
    parser.add_argument("--output", default="evaluation_metrics.md")
    args = parser.parse_args()

    rows = load_rows(args.input)
    if not rows:
        print(f"No rows found in {args.input}. Run run_evaluation.py first.")
        return

    overall = compute(rows)
    per_category = by_category(rows)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    print(f"\n=== Evaluation Metrics (n={overall['n_tests']}) ===")
    print(f"Tool selection accuracy : {pct(overall['tool_selection_accuracy'])}  (target >= 85%)")
    print(f"Argument accuracy       : {pct(overall['argument_accuracy'])}  (target >= 80%)  "
          f"[{overall['argument_checks_matched']}/{overall['argument_checks_total']} checks]")
    print(f"Task completion rate    : {pct(overall['task_completion_rate'])}  (target >= 80%)")
    print(f"Approval compliance     : {pct(overall['approval_compliance'])}  (target = 100%)  "
          f"[{overall['approval_tests_n']} approval-relevant tests]")
    print(f"Invalid action rate     : {pct(overall['invalid_action_rate'])}  (target < 10%)")
    print(f"Average response time   : {ms(overall['average_response_time_ms'])}")
    print(f"Recovery rate           : {pct(overall['recovery_rate'])}  "
          f"[{overall['recovery_tests_n']} recovery tests]")

    md = render_markdown(overall, per_category, generated_at)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"\nWrote {args.output} — paste its contents to Claude to generate Document 5.")


if __name__ == "__main__":
    main()
